export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAILURE = 'ORDER_UPDATE_FAILURE';
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAILURE = 'ORDER_PAY_FAILURE';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_SHIPPED_REQUEST = 'ORDER_SHIPPED_REQUEST';
export const ORDER_SHIPPED_SUCCESS = 'ORDER_SHIPPED_SUCCESS';
export const ORDER_SHIPPED_FAILURE = 'ORDER_SHIPPED_FAILURE';
export const ORDER_SHIPPED_RESET = 'ORDER_SHIPPED_RESET';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAILURE = 'ORDER_DELIVER_FAILURE';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const ORDER_RETURN_REQUEST = 'ORDER_RETURN_REQUEST';
export const ORDER_RETURN_SUCCESS = 'ORDER_RETURN_SUCCESS';
export const ORDER_RETURN_FAILURE = 'ORDER_RETURN_FAILURE';
export const ORDER_RETURN_RESET = 'ORDER_RETURN_RESET';

export const ORDER_USER_LIST_REQUEST = 'ORDER_USER_LIST_REQUEST';
export const ORDER_USER_LIST_SUCCESS = 'ORDER_USER_LIST_SUCCESS';
export const ORDER_USER_LIST_FAILURE = 'ORDER_USER_LIST_FAILURE';
export const ORDER_USER_LIST_RESET = 'ORDER_USER_LIST_RESET';

export const ORDER_ALL_LIST_REQUEST = 'ORDER_ALL_LIST_REQUEST';
export const ORDER_ALL_LIST_SUCCESS = 'ORDER_ALL_LIST_SUCCESS';
export const ORDER_ALL_LIST_FAILURE = 'ORDER_ALL_LIST_FAILURE';
